# File: tsdb-bench-test-config.yml

# V3IO NGINX
v3ioUrl: "localhost:8081"

# V3IO container identifier
container: "bigdata"

# Relative time, i.e. now() - startTimeOffset
startTimeOffset: "24h"

# Interval in milliseconds between samples
sampleStepSize: 1000

# should be in range [1..26]
namesCount: 26

#
namesDiversity: 200

# should be in range [1..26]
labelsCount: 10

#
labelsDiversity: 10

# should be in range [1..26]
labelValuesCount: 10

#
labelsValueDiversity: 10
